definitions:
  gin_http.ResponseJSON:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
info:
  contact: {}
paths:
  /admin/menu/list:
    get:
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: 获取后台管理菜单
  /api/v1/article/add:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: 用户id
        in: formData
        name: user_id
        required: true
        type: integer
      - description: 内容
        in: formData
        name: content
        required: true
        type: string
      - description: 标签
        in: formData
        items:
          type: integer
        name: tag_id
        type: array
      - description: image
        in: formData
        name: image
        required: true
        type: file
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: 添加文章
  /api/v1/article/addTags/{id}:
    post:
      parameters:
      - description: 文章ID
        in: path
        name: id
        required: true
        type: integer
      - description: 标签ID
        in: formData
        items:
          type: integer
        name: tag_id
        type: array
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: 添加文章标签
  /api/v1/article/delete/{id}:
    delete:
      parameters:
      - description: 文章ID
        in: path
        name: id
        required: true
        type: integer
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: 删除文章
  /api/v1/article/deleteTags/{id}:
    delete:
      parameters:
      - description: 文章ID
        in: path
        name: id
        required: true
        type: integer
      - description: 标签ID
        in: formData
        items:
          type: integer
        name: tag_id
        required: true
        type: array
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: 删除文章标签
  /api/v1/article/getList:
    get:
      parameters:
      - description: Page
        in: query
        name: page
        type: integer
      produces:
      - application/json
      responses: {}
      summary: 获取文章列表
  /api/v1/article/recover/{id}:
    post:
      parameters:
      - description: 文章ID
        in: path
        name: id
        required: true
        type: integer
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: 恢复文章
  /api/v1/tag/add:
    post:
      parameters:
      - description: Name
        in: formData
        name: name
        required: true
        type: string
      - description: CreatedBy
        in: formData
        name: created_by
        type: string
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin_http.ResponseJSON'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin_http.ResponseJSON'
        "10001":
          description: ""
          schema:
            $ref: '#/definitions/gin_http.ResponseJSON'
        "10006":
          description: ""
          schema:
            $ref: '#/definitions/gin_http.ResponseJSON'
      summary: 新增标签
  /api/v1/tag/clear/{id}:
    delete:
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: 清理标签(硬删除)
  /api/v1/tag/delete/{id}:
    delete:
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin_http.ResponseJSON'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin_http.ResponseJSON'
        "10008":
          description: ""
          schema:
            $ref: '#/definitions/gin_http.ResponseJSON'
      summary: 删除标签
  /api/v1/tag/getArticles/{id}:
    get:
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin_http.ResponseJSON'
      summary: 获取该标签的所有文章
  /api/v1/tag/getList:
    get:
      parameters:
      - description: Page
        in: query
        name: page
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin_http.ResponseJSON'
      summary: 获取标签列表
  /api/v1/tag/recover/{id}:
    post:
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: 恢复标签
  /api/v1/tag/update/{id}:
    put:
      parameters:
      - description: ID
        in: path
        name: id
        required: true
        type: integer
      - description: Name
        in: formData
        name: name
        required: true
        type: string
      - description: Modifiedby
        in: formData
        name: modified_by
        type: string
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin_http.ResponseJSON'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin_http.ResponseJSON'
        "10007":
          description: ""
          schema:
            $ref: '#/definitions/gin_http.ResponseJSON'
      summary: 修改标签
  /delete_user:
    delete:
      parameters:
      - description: id
        in: formData
        name: id
        required: true
        type: integer
      - description: username
        in: formData
        name: username
        required: true
        type: string
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin_http.ResponseJSON'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin_http.ResponseJSON'
        "20008":
          description: ""
          schema:
            $ref: '#/definitions/gin_http.ResponseJSON'
      summary: 注销用户
  /update_password:
    put:
      parameters:
      - description: id
        in: formData
        name: id
        required: true
        type: integer
      - description: password
        in: formData
        name: password
        required: true
        type: string
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin_http.ResponseJSON'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin_http.ResponseJSON'
        "20009":
          description: ""
          schema:
            $ref: '#/definitions/gin_http.ResponseJSON'
      summary: 修改用户密码
  /upload:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: image
        in: formData
        name: image
        required: true
        type: file
      - description: token
        in: query
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 上传图片
      tags:
      - file
  /user/list:
    get:
      parameters:
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin_http.ResponseJSON'
      summary: 用户列表
  /user/login:
    post:
      parameters:
      - description: username
        in: formData
        name: username
        required: true
        type: string
      - description: password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin_http.ResponseJSON'
        "20005":
          description: ""
          schema:
            $ref: '#/definitions/gin_http.ResponseJSON'
      summary: 用户登录
  /user/refreshToken/{id}:
    post:
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: integer
      - description: uuid
        in: header
        name: uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin_http.ResponseJSON'
      summary: 更新Token
  /user/register:
    post:
      parameters:
      - description: username
        in: formData
        name: username
        required: true
        type: string
      - description: password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin_http.ResponseJSON'
        "20006":
          description: ""
          schema:
            $ref: '#/definitions/gin_http.ResponseJSON'
        "20007":
          description: ""
          schema:
            $ref: '#/definitions/gin_http.ResponseJSON'
      summary: 用户注册
swagger: "2.0"
