definitions:
  gin_http.ResponseJSON:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/tags:
    get:
      parameters:
      - description: Name
        in: query
        name: name
        type: string
      - description: State
        in: query
        name: state
        type: integer
      - description: CreatedBy
        in: query
        name: created_by
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 获取多个文章标签
    post:
      parameters:
      - description: Name
        in: query
        name: name
        required: true
        type: string
      - description: CreatedBy
        in: query
        name: created_by
        type: string
      - description: token
        in: query
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "10000":
          description: '{"code":10001,"data":{},"msg":"TOKEN为空"}'
          schema:
            type: string
        "10001":
          description: '{"code":10001,"data":{},"msg":"已存在该标签"}'
          schema:
            type: string
      summary: 新增文章标签
  /api/v1/tags/:id:
    delete:
      parameters:
      - description: Name
        in: query
        name: name
        type: string
      - description: token
        in: query
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
        "10000":
          description: '{"code":10001,"data":{},"msg":"TOKEN为空"}'
          schema:
            type: string
        "10002":
          description: '{"code":10002,"data":{},"msg":"标签不存在"}'
          schema:
            type: string
      summary: 删除文章标签
  /delete_user:
    delete:
      parameters:
      - description: id
        in: formData
        name: id
        required: true
        type: integer
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin_http.ResponseJSON'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin_http.ResponseJSON'
        "20008":
          description: ""
          schema:
            $ref: '#/definitions/gin_http.ResponseJSON'
      summary: 注销用户
  /login:
    post:
      parameters:
      - description: username
        in: formData
        name: username
        required: true
        type: string
      - description: password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin_http.ResponseJSON'
        "20005":
          description: ""
          schema:
            $ref: '#/definitions/gin_http.ResponseJSON'
      summary: 用户登录
  /register:
    post:
      parameters:
      - description: username
        in: formData
        name: username
        required: true
        type: string
      - description: password
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin_http.ResponseJSON'
        "20006":
          description: ""
          schema:
            $ref: '#/definitions/gin_http.ResponseJSON'
        "20007":
          description: ""
          schema:
            $ref: '#/definitions/gin_http.ResponseJSON'
      summary: 用户注册
  /update_password:
    put:
      parameters:
      - description: id
        in: formData
        name: id
        required: true
        type: integer
      - description: password
        in: formData
        name: password
        required: true
        type: string
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin_http.ResponseJSON'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin_http.ResponseJSON'
        "20009":
          description: ""
          schema:
            $ref: '#/definitions/gin_http.ResponseJSON'
      summary: 修改用户密码
  /upload:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: image
        in: formData
        name: image
        required: true
        type: file
      - description: token
        in: query
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"data":{},"msg":"ok"}'
          schema:
            type: string
      summary: 上传图片
      tags:
      - file
swagger: "2.0"
